export const TEXT_INJURIES = [
	{ content: 'Nasal Congestion' },
	{ content: 'Cough' },
	{ content: 'Abdominal Pain' },
	{ content: 'Broken Toe' },
	{ content: 'Choking' },
	{ content: 'Diarrhea' },
	{ content: 'Heat Exhaustion' },
	{ content: 'Heat Stroke' },
	{ content: 'Nose Bleed' },
	{ content: 'Rectal Bleeding' },
	{ content: 'Testicle Pain' },
	{ content: 'Vertigo' },
	{ content: 'Eye Injury' },
	{ content: 'Food Poisoning' },
	{ content: 'Convulsion' },
	{ content: 'Head Injury' },
	{ content: 'Fainting' },
	{ content: 'Headache' },
	{ content: 'Cold' },
	{ content: 'Drowning' },
	{ content: 'Chest Pain' },
	{ content: 'Dehydration' },
	{ content: 'Cut' },
	{ content: 'Burn' },
	{ content: 'Abrasion' },
	{ content: 'Sting' },
	{ content: 'Splinter' },
	{ content: 'Sprain' },
	{ content: 'Pulled Muscle' },
	{ content: 'Sun Burn' },
	{ content: 'Strain' },
	{ content: 'Chemical Burn' },
	{ content: 'Rash' },
	{ content: 'Snake Bite' },
	{ content: 'Bruise' },
	{ content: 'Fracture' },
	{ content: 'Stroke' },
	{ content: 'Bleeding' },
	{ content: 'Fever' },
	// { content: 'Dizziness' },
	// { content: 'Heart Attack' },
	// { content: 'Seizure' },
];

export const IMAGE_INJURIES = [
	{ content: 'Abrasions', source: 'abrasions.png' },
	{ content: 'Burns', source: 'burns.png' },
	{ content: 'Bruise', source: 'bruise.png' },
	{ content: 'Cuts', source: 'cuts.png' },
	{ content: 'Laseration', source: 'sting.png' },
];
