export const TEXT_INJURIES = [
	{ content: 'Burns' },
	{ content: 'Cuts' },
	{ content: 'Abrasions' },
	{ content: 'Stings' },
	{ content: 'Splinter' },
	{ content: 'Sprains' },
	{ content: 'Strains' },
	{ content: 'Bruises' },
	{ content: 'Pulled Muscle' },
	{ content: 'Sun Burn' },
	{ content: 'Chemical Burn' },
	{ content: 'Rash' },
	{ content: 'Snake Bite' },
	{ content: 'Bleeding' },
	{ content: 'Fracture' },
	{ content: 'Fever' },
	{ content: 'Convulsions' },
	{ content: 'Chest Pain' },
	{ content: 'Stroke' },
	{ content: 'Dehydration' },
	{ content: 'Nasal Congestion' },
	{ content: 'Cough' },
	{ content: 'Skin Problems' },
	{ content: 'Abdominal Pain' },
	{ content: 'Broken Toe' },
	{ content: 'Choking' },
	{ content: 'Diarrhea' },
	{ content: 'Heat Exhaustion' },
	{ content: 'Heat Stroke' },
	{ content: 'Nose Bleed' },
	{ content: 'Rectal Bleeding' },
	{ content: 'Testicle Pain' },
	{ content: 'Vertigo' },
	{ content: 'Eye Injury' },
	{ content: 'Food Poison' },
	{ content: 'Seizure' },
	{ content: 'Head Injury' },
	{ content: 'Fainting' },
	{ content: 'Headache' },
	{ content: 'Cold' },
	{ content: 'Drowning' },
];

export const IMAGE_INJURIES = [
	{ content: 'Burns', source: 'burns.png' },
	{ content: 'Cuts', source: 'cuts.png' },
	{ content: 'Abrasions', source: 'abrasions.png' },
	{ content: 'Sting', source: 'sting.png' },
	{ content: 'Splinter', source: 'splinter.png' },
	{ content: 'Sprain', source: 'sprain.png' },
	{ content: 'Bruise', source: 'bruise.png' },
	{ content: 'Frost Bite', source: 'frost-bite.png' },
	{ content: 'Sun Burn', source: 'sun-burn.png' },
	{ content: 'Rashes', source: 'rashes.png' },
	{ content: 'Snake Bite', source: 'snake-bite.png' },
];
