export const TEXT_INJURIES = [
	{ content: 'Burns' },
	{ content: 'Cuts' },
	{ content: 'Abrasions' },
	{ content: 'Stings' },
	{ content: 'Splinter' },
	{ content: 'Sprains' },
	{ content: 'Strains' },
	{ content: 'Bruises' },
	{ content: 'Normal Wound' },
	{ content: 'Frost Bite' },
	{ content: 'Insect Bites' },
	{ content: 'Pulled Muscle' },
	{ content: 'Sun Burn' },
	{ content: 'Chemical Burn' },
	{ content: 'Rash' },
	{ content: 'Snake Bite' },
	{ content: 'Animal Bite' },
	{ content: 'Bleeding' },
	{ content: 'Fracture' },
	{ content: 'Fever' },
	{ content: 'Convulsions' },
	{ content: 'Chest Pain' },
	{ content: 'Stroke' },
	{ content: 'Dehydration' },
	{ content: 'Nasal Congestion' },
	{ content: 'Cough' },
	{ content: 'Gastrointestinal Problems' },
	{ content: 'Skin Problems' },
	{ content: 'Abdominal Pain' },
	{ content: 'Broken Toe' },
	{ content: 'Choking' },
	{ content: 'Diarrhea' },
	{ content: 'Heat Exhaustion' },
	{ content: 'Heat Stroke' },
	{ content: 'Nose Bleed' },
	{ content: 'Rectal Bleeding' },
	{ content: 'Testicle Pain' },
	{ content: 'Vertigo' },
	{ content: 'Eye Injury' },
	{ content: 'Food Poison' },
	{ content: 'Seizure' },
	{ content: 'Head Injury' },
	{ content: 'Fainting' },
	{ content: 'Headache' },
	{ content: 'Cold' },
	{ content: 'Drowning' },
	{ content: 'CPR' },
];

export const IMAGE_INJURIES = [
	{ content: 'Burns', source: 'burns.png' },
	{ content: 'Cuts' },
	{ content: 'Abrasions' },
	{ content: 'Stings' },
	{ content: 'Splinter' },
	{ content: 'Sprains' },
	{ content: 'Strains' },
	{ content: 'Bruises' },
	{ content: 'Normal Wound' },
	{ content: 'Frost Bite' },
	{ content: 'Insect Bites' },
	{ content: 'Pulled Muscle' },
	{ content: 'Sun Burn' },
	{ content: 'Chemical Burn' },
	{ content: 'Rash' },
	{ content: 'Snake Bite' },
	{ content: 'Animal Bite' },
];
